### ISSUE TITLE
Sylon Roadmap

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/sylon#76]
## Components
- [ ] Button
- [ ] Chip
- [ ] Tabs
- [ ] Input
  - [ ] NumberInput
  - [ ] TextInput
  - [ ] PasswordInput
  - [ ] MultiLineInput
- [ ] Boolean states
  - [ ] Checkbox
  - [ ] Radio
  - [ ] ToggleSwitch
- [ ] Overlays
  - [ ] ContextMenu (right-click) 
  - [ ] SelectMenu (select an item)
  - [ ] DropdownMenu (select an action)
  - [ ] NavigationMenu
  - [ ] Dialog
  - [ ] Tooltip

## Templates

- [ ] Template on Stackblitz
- [ ] Template on CodeSandbox
